# fly.toml file generated for rough-flower-2130 on 2023-03-23T14:54:58+02:00

app = "rough-flower-2130"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "arn"
processes = []

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
